GET http://localhost:4000/api/test

###
GET http://localhost:4000/api/listall

###
GET http://localhost:4000/api/listone/91


###
POST http://localhost:4000/api/save
Content-Type: application/json

{
    "title":"Prueba 5",
    "content":"content prueba 5",
    "importance":"dark"
}

###
DELETE http://localhost:4000/api/delete/102

###
PUT http://localhost:4000/api/update/91
Content-Type: application/json

{
    "title":"prueba edicion",
    "content":"contenido prueba",
    "importance":"danger"
}

###

GET http://localhost:4000/api/getbyname/tac

